### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by vinamelody** [Subito-it/Cachi#6]
Hi, my bad, I'm trying this but stuck with the usage.
So if my tests.xcresult file is in `~/Downloads/xccov/test.xcresult` what will be the command to run it?

I installed via brew and tried these commands but nothing happened

```
~/Downloads > cachi -p=6000 xccov/
~/Downloads > cachi -p=6000 xccov
~/Downloads > cachi --port=6000 xccov/
~/Downloads > cachi --port=6000 xccov
~/Downloads/xccov > cachi --port=6000 .
~/Downloads/xccov > cachi --port=6000 test.xcresult
```

**Comment by tcamin** [comment]
The problem may be related to [choosing port 600](https://stackoverflow.com/questions/29297390/whats-special-about-port-6000), try a different port like for example 6001.
